# Data Analytics Internship Project

## Project 1: Data Cleaning & Preparation

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("/content/Dataset for Data Analytics.xlsx")

df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [ ]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [ ]:
df["CouponCode"] = df["CouponCode"].fillna("No Coupon")

In [ ]:
print("Duplicate rows:", df.duplicated().sum())
df = df.drop_duplicates()

Duplicate rows: 0

In [ ]:
text_columns = [
    "Product",
    "PaymentMethod",
    "OrderStatus",
    "ReferralSource"
]

for col in text_columns:
    df[col] = df[col].str.strip().str.title()

In [ ]:
df["Date"] = pd.to_datetime(df["Date"])
df["Date"] = df["Date"].dt.strftime("%Y-%m-%d")

In [ ]:
df["CalculatedTotal"] = df["Quantity"] * df["UnitPrice"]

mismatch = df[df["CalculatedTotal"] != df["TotalPrice"]]

print(mismatch)

        OrderID        Date CustomerID  Product  Quantity  UnitPrice  \
2     ORD200002  2024-02-27     C81728   Tablet         5     550.68
10    ORD200010  2023-12-29     C43443   Tablet         5     625.97
11    ORD200011  2024-02-17     C93861  Monitor         3      49.14
32    ORD200032  2023-05-01     C12388   Tablet         5     536.72
41    ORD200041  2023-12-05     C20212  Monitor         3     611.45
...         ...         ...        ...      ...       ...        ...
1122  ORD201122  2023-06-07     C38840  Monitor         5     678.19
1136  ORD201136  2023-09-24     C71899   Tablet         3     668.33
1175  ORD201175  2024-09-10     C62512  Printer         3      91.74
1189  ORD201189  2024-08-17     C96136   Tablet         5     389.22
1192  ORD201192  2024-02-28     C72007    Chair         3     432.85

     ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart  \
2        512 Main St   Credit Card   Cancelled    TRK42903982            8
10       333 Main St   Credit Card    Returned    TRK98859248            9
11       831 Main St        Online    Returned    TRK48234646            7
32       830 Main St          Cash   Delivered    TRK99261395           10
41       657 Main St     Gift Card     Pending    TRK69733327            4
...              ...           ...         ...            ...          ...
1122     766 Main St        Online    Returned    TRK32496970            8
1136     799 Main St     Gift Card     Pending    TRK34856025            4
1175     368 Main St    Debit Card    Returned    TRK24139954            8
1189     149 Main St          Cash   Cancelled    TRK60856682            7
1192     999 Main St        Online     Pending    TRK16240916            4

     CouponCode ReferralSource  TotalPrice  CalculatedTotal
2      FREESHIP          Email     2753.40          2753.40
10     WINTER15      Instagram     3129.85          3129.85
11       SAVE10          Email      147.42           147.42
32    No Coupon          Email     2683.60          2683.60
41     FREESHIP      Instagram     1834.35          1834.35
...         ...            ...         ...              ...
1122  No Coupon       Facebook     3390.95          3390.95
1136   WINTER15       Facebook     2004.99          2004.99
1175   FREESHIP       Referral      275.22           275.22
1189  No Coupon       Referral     1946.10          1946.10
1192  No Coupon      Instagram     1298.55          1298.55

[107 rows x 15 columns]

In [ ]:
df["CalculatedTotal"] = (df["Quantity"] * df["UnitPrice"]).round(2)

mismatch = df[df["CalculatedTotal"] != df["TotalPrice"]]

print(mismatch)

        OrderID        Date CustomerID  Product  Quantity  UnitPrice  \
39    ORD200039  2025-02-27     C96664  Printer         3     256.46
66    ORD200066  2024-11-15     C18104    Chair         5     127.18
85    ORD200085  2024-09-09     C14553   Tablet         3     146.73
111   ORD200111  2025-05-07     C95271     Desk         3     309.22
113   ORD200113  2024-01-17     C65905   Laptop         5     190.08
123   ORD200123  2023-07-06     C86064     Desk         3     278.04
190   ORD200190  2024-08-31     C35483  Printer         3     223.70
202   ORD200202  2025-02-06     C36938  Monitor         3     253.98
225   ORD200225  2024-03-13     C99879    Phone         3     273.96
254   ORD200254  2023-12-26     C10866  Monitor         3     263.19
310   ORD200310  2024-02-24     C85863  Printer         3     132.48
352   ORD200352  2023-08-31     C26637    Chair         5     173.96
449   ORD200449  2024-08-26     C91518   Tablet         3     253.05
514   ORD200514  2023-04-16     C15629  Printer         3     304.15
592   ORD200592  2024-04-23     C42306    Phone         3     204.27
604   ORD200604  2025-06-22     C99214    Chair         3      32.62
871   ORD200871  2024-05-16     C93768   Tablet         3     324.30
875   ORD200875  2023-08-03     C25918   Laptop         5     133.39
938   ORD200938  2023-07-12     C39017    Chair         3     331.46
991   ORD200991  2024-05-09     C10211     Desk         5     127.18
993   ORD200993  2024-04-06     C61384  Monitor         3     267.45
1018  ORD201018  2023-07-08     C77499   Laptop         3     182.48
1091  ORD201091  2024-10-08     C16400   Laptop         3     209.48
1118  ORD201118  2024-05-24     C58168    Phone         3     251.48
1126  ORD201126  2024-07-22     C34337    Phone         5     190.11
1157  ORD201157  2024-05-29     C25841  Monitor         3     301.55
1163  ORD201163  2024-06-11     C30643   Laptop         3     306.29
1166  ORD201166  2023-07-31     C95568    Chair         3     324.47
1194  ORD201194  2023-11-19     C29885  Printer         3     189.44

     ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart  \
39       666 Main St   Credit Card   Delivered    TRK85508960            4
66       715 Main St          Cash   Cancelled    TRK15488568            9
85       768 Main St          Cash   Delivered    TRK93538334            8
111      620 Main St        Online   Cancelled    TRK74904969            7
113      605 Main St          Cash     Shipped    TRK73954365            9
123      727 Main St        Online   Delivered    TRK62182901            5
190      725 Main St          Cash    Returned    TRK79638203            3
202      636 Main St   Credit Card   Cancelled    TRK52522904            3
225      692 Main St    Debit Card    Returned    TRK50246700            8
254      770 Main St        Online   Delivered    TRK34809583            5
310      968 Main St        Online     Shipped    TRK16094218            4
352      995 Main St    Debit Card     Pending    TRK59546992            8
449      286 Main St        Online     Pending    TRK48688724            3
514      492 Main St     Gift Card     Shipped    TRK64926044            3
592      938 Main St        Online    Returned    TRK15499648            4
604      252 Main St    Debit Card   Delivered    TRK81368481            6
871      720 Main St    Debit Card     Pending    TRK22024707            8
875      203 Main St   Credit Card   Delivered    TRK66473392            6
938      696 Main St   Credit Card   Cancelled    TRK91155214            6
991      598 Main St    Debit Card   Cancelled    TRK68938335           10
993      576 Main St     Gift Card   Delivered    TRK33323210            5
1018     209 Main St          Cash   Delivered    TRK20703086            3
1091     123 Main St    Debit Card     Pending    TRK57771859            4
1118     359 Main St   Credit Card    Returned    TRK99102265            4
1126     325 Main St          Cash   Delivered    TRK36195559            7
1157     242 Main St    Debit Card   Delivered    TRK21451375            5
1163     966 Main St   Credit Card    Returned    TRK19477485            7
1166     971 Main St          Cash   Delivered    TRK37075292            4
1194     725 Main St          Cash     Pending    TRK62067865            4

     CouponCode ReferralSource  TotalPrice  CalculatedTotal
39       SAVE10       Referral      769.38           769.38
66       SAVE10       Referral      635.90           635.90
85     FREESHIP          Email      440.19           440.19
111    FREESHIP         Google      927.66           927.66
113    FREESHIP      Instagram      950.40           950.40
123   No Coupon      Instagram      834.12           834.12
190      SAVE10          Email      671.10           671.10
202    FREESHIP          Email      761.94           761.94
225      SAVE10         Google      821.88           821.88
254   No Coupon      Instagram      789.57           789.57
310   No Coupon       Referral      397.44           397.44
352    WINTER15      Instagram      869.80           869.80
449   No Coupon      Instagram      759.15           759.15
514    WINTER15      Instagram      912.45           912.45
592   No Coupon         Google      612.81           612.81
604   No Coupon       Facebook       97.86            97.86
871    FREESHIP          Email      972.90           972.90
875    FREESHIP       Referral      666.95           666.95
938    WINTER15       Referral      994.38           994.38
991    FREESHIP         Google      635.90           635.90
993    WINTER15      Instagram      802.35           802.35
1018  No Coupon      Instagram      547.44           547.44
1091  No Coupon          Email      628.44           628.44
1118  No Coupon          Email      754.44           754.44
1126     SAVE10         Google      950.55           950.55
1157   FREESHIP         Google      904.65           904.65
1163   WINTER15      Instagram      918.87           918.87
1166   WINTER15          Email      973.41           973.41
1194   FREESHIP          Email      568.32           568.32

In [ ]:
mismatch = df[abs(df["CalculatedTotal"] - df["TotalPrice"]) > 0.01]

print(mismatch)

Empty DataFrame
Columns: [OrderID, Date, CustomerID, Product, Quantity, UnitPrice, ShippingAddress, PaymentMethod, OrderStatus, TrackingNumber, ItemsInCart, CouponCode, ReferralSource, TotalPrice, CalculatedTotal]
Index: []

In [ ]:
df.to_excel("Cleaned_Ecommerce_Dataset.xlsx", index=False)

print("Dataset cleaned successfully!")

Dataset cleaned successfully!

In [ ]:
from google.colab import files

files.download("Cleaned_Ecommerce_Dataset.xlsx")

# Key Insights / Observations

* Missing values in the `CouponCode` column were handled successfully.
* Duplicate records were checked and removed to improve data quality.
* Text and date formatting were standardized for consistency.
* TotalPrice values were validated using Quantity × UnitPrice calculations.
* The cleaned dataset is now ready for further analysis and visualization.